services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    container_name: gitea
    environment:
      - USER_UID=${USER_UID:-1000}
      - USER_GID=${USER_GID:-1000}
      - GITEA__database__DB_TYPE=${GITEA__database__DB_TYPE:-sqlite3}
      - GITEA__server__DOMAIN=${DOMAIN}
      - GITEA__server__SSH_DOMAIN=${SSH_DOMAIN}
      - GITEA__server__HTTP_PORT=${HTTP_PORT}
      - GITEA__server__ROOT_URL=http://${DOMAIN}:${HTTP_PORT}/
      - GITEA__actions__ENABLED=${GITEA__actions__ENABLED:-true}
    restart: always
    networks:
      gitea_network:
        aliases:
          - ${DOMAIN}
    volumes:
      - ${VOLUME_ROOT}/gitea_data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "${HTTP_PORT}:3000"
      - "${SSH_PORT:-2222}:22"

  runner:
    build:
      context: .
      dockerfile: Dockerfile.runner
    container_name: gitea_runner
    restart: always
    environment:
      # O runner precisa acessar a instância do Gitea na mesma rede Docker
      GITEA_INSTANCE_URL: "http://${DOMAIN}:3000"
      GITEA_RUNNER_REGISTRATION_TOKEN: "${GITEA_RUNNER_REGISTRATION_TOKEN:-cole_seu_token_aqui_depois}"
      GITEA_RUNNER_NAME: "local-runner"
      GITEA_RUNNER_LABELS: "ubuntu-latest:docker://node:20-bullseye,ubuntu-22.04:docker://node:20-bullseye"
      CONFIG_FILE: /config.yaml
    networks:
      - gitea_network
    volumes:
      - ${VOLUME_ROOT}/gitea_runner_data:/data
      # Montar o socket do docker para conseguir rodar containers (CI) de dentro do runner
      - /var/run/docker.sock:/var/run/docker.sock 
    depends_on:
      - server

  registry:
    image: registry:2
    container_name: docker_registry
    restart: always
    ports:
      - "5000:5000"
    networks:
      - gitea_network
    volumes:
      - ${VOLUME_ROOT}/registry_data:/var/lib/registry

  runner-setup:
    image: docker:cli
    container_name: gitea_runner_setup
    depends_on:
      - server
      - runner
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: >
      /bin/sh -c "
        echo 'Aguardando o Gitea iniciar...';
        sleep 10;
        TOKEN=\$$(docker exec gitea su git -c 'gitea --config /data/gitea/conf/app.ini actions generate-runner-token');
        if [ -n \"\$$TOKEN\" ]; then
          echo 'Registrando runner...';
          docker exec gitea_runner act_runner register --instance http://notebook-server:3000 --token \"\$$TOKEN\" --no-interactive;
          echo 'Iniciando o daemon do runner...';
          docker exec -d gitea_runner act_runner daemon;
          echo 'Runner registrado com sucesso.';
        else
          echo 'Falha ao gerar token do runner.';
        fi
      "

networks:
  gitea_network:
    driver: bridge
